### ISSUE TITLE
transaction given in readme dosent work

### ISSUE THREAD

**Issue by davehaughton1** [tendermint/merkleeyes#4]
Hi, I run merkleeys server:

`merkleeyes server --address "tcp://127.0.0.1:46659" --tmsp "socket"`

Then I run the tmsp-cli:

`tmsp-cli --address "tcp://127.0.0.1:46659" --tmsp "socket" console`

I give the transaction and get response :
`> append_tx 0x010104657269630107636c6170746f6e`
`-> code: EncodingError`
`-> log: Error getting key: Varint overflow`

**Comment by ebuchman** [comment]
Hi sorry about this. Can you try checking out the develop branch of tmsp and re-installing? Alternatively, use `x010104657269630107636c6170746f6e` instead of `0x010104657269630107636c6170746f6e` (ie. drop the zero in front. This simple formatting change should be merged to master in the next day or two.

**Comment by srmo** [comment]
Retested: 
develop works with the correct format. Master works when omitting the leading 0

On develop omitting leads to 
`-> code: UnknownRequest`
`-> log: Unexpected AppendTx type byte 78`

**Comment by davehaughton1** [comment]
Thanks, I got it working with the develop branch of tmsp.
